/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Fitness_Grandma_BodyGeo_1: THREE.SkinnedMesh
    Fitness_Grandma_BodyGeo_2: THREE.SkinnedMesh
    Fitness_Grandma_BrowsAnimGeo: THREE.SkinnedMesh
    Fitness_Grandma_EyesAnimGeo: THREE.SkinnedMesh
    Fitness_Grandma_MouthAnimGeo: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    Grandma_MAT: THREE.MeshStandardMaterial
    Lens_MAT: THREE.MeshStandardMaterial
    FitGrandma_Brows_MAT1: THREE.MeshStandardMaterial
    FitGrandma_Eyes_MAT1: THREE.MeshStandardMaterial
    FitGrandma_Mouth_MAT1: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Armature|mixamo.com|Layer0'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

const DancingModel = (props: JSX.IntrinsicElements['group']): JSX.Element => {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(
    '/models/dancing.glb'
  ) as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  useEffect(() => {
    actions['Armature|mixamo.com|Layer0'].play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Armature"
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.02, 0.02, 0.02]}
      >
        <primitive object={nodes.Hips} />
        <skinnedMesh
          geometry={nodes.Fitness_Grandma_BodyGeo_1.geometry}
          material={materials.Grandma_MAT}
          skeleton={nodes.Fitness_Grandma_BodyGeo_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Fitness_Grandma_BodyGeo_2.geometry}
          material={materials.Lens_MAT}
          skeleton={nodes.Fitness_Grandma_BodyGeo_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Fitness_Grandma_BrowsAnimGeo.geometry}
          material={materials.FitGrandma_Brows_MAT1}
          skeleton={nodes.Fitness_Grandma_BrowsAnimGeo.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Fitness_Grandma_EyesAnimGeo.geometry}
          material={materials.FitGrandma_Eyes_MAT1}
          skeleton={nodes.Fitness_Grandma_EyesAnimGeo.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Fitness_Grandma_MouthAnimGeo.geometry}
          material={materials.FitGrandma_Mouth_MAT1}
          skeleton={nodes.Fitness_Grandma_MouthAnimGeo.skeleton}
        />
      </group>
    </group>
  )
}
export default DancingModel

useGLTF.preload('/models/dancing.glb')
